import { Hono } from 'hono';
import { authRoutes } from './auth.routes.js';
import { userRoutes } from './users.routes.js';
import { adminRoutes } from './admin.routes.js';
import { settingsRoutes } from './settings.routes.js';
import { productRoutes } from './products.routes.js';
import { inventoryRoutes } from './inventory.routes.js';
import { supplierRoutes } from './suppliers.routes.js';
import { goodsReceiptRoutes } from './goods-receipts.routes.js';
import { customerRoutes } from './customers.routes.js';
import { salesRoutes } from './sales.routes.js';
import { syncRoutes } from './sync.routes.js';
import { labelRoutes } from './labels.routes.js';
import { creditRoutes } from './credit.routes.js';
import { expenseRoutes } from './expenses.routes.js';
import { cashRegisterRoutes } from './cash-register.routes.js';
import { reportRoutes } from './reports.routes.js';
import type { AppEnv } from '../types/hono.js';

export const routes = new Hono<AppEnv>();

routes.route('/auth', authRoutes);
routes.route('/users', userRoutes);
routes.route('/admin', adminRoutes);
routes.route('/settings', settingsRoutes);
routes.route('/products', productRoutes);
routes.route('/inventory', inventoryRoutes);
routes.route('/suppliers', supplierRoutes);
routes.route('/goods-receipts', goodsReceiptRoutes);
routes.route('/customers', customerRoutes);
routes.route('/sales', salesRoutes);
routes.route('/sync', syncRoutes);
routes.route('/labels', labelRoutes);
routes.route('/credit', creditRoutes);
routes.route('/expenses', expenseRoutes);
routes.route('/cash-register', cashRegisterRoutes);
routes.route('/reports', reportRoutes);
